### ISSUE TITLE
make a way for people to import schematics

### ISSUE THREAD

**Issue by 1980s-housewife** [TheDeus-Group/TFM-4.3-Reloaded#25]
(the ops want it)
![image](https://user-images.githubusercontent.com/17932849/159775700-a66939e7-299a-46fb-8c1e-0c4a85b8b039.png)

**Comment by saxnbt** [comment]
will make

**Comment by business-goose** [comment]
this is a bad idea

**Comment by 1980s-housewife** [comment]
allink is badl
